travis:
  secure:
    BINSTAR_TOKEN: nh/9wqW045CBJddACKbckEJdFXLdEo6DJavD4EebJsCTo7Bfky+TqhdNjcIVuTWXm8uSKG3XADTqYqVpJiY0JMbIcIDgBypTO5mxSX43AFL87lk1rLkMqqiR9d5bsjLbvWQz2ccPBxypkRYbm4CY92Zy7GS5wesUyNF/G8d2/MzfphsXt1C1pY6aTh7k7n4IX29LVuTUFNsRyhRuTUfUL2FpeAEqpHk7MK5IM4A1FbNka90t4MxDUaeQnhTrSNP2W1RNFrIizcGas2IeHLWRsmeCqZr59OYer1iIeQOdFQEIkOjdpjtD9PoGULW6i96IyXbf0JyHqYbZe0ao8HNPJ84vRBXpt1mDtXlPIDpEHMwL0CFf8IXVL3Znh+LXFKAUMntHL6ggCnlYbJC7AVoC9fzP4WBU1G9ok33Kt4I4qZLRADM1x3ATBuDYDJRrtjkmaRfxGtZGOEliIcpNTDd0uMaaFyO3QilK58tIMy3eMKM9FrWO7qtEg79wPr9HzBl+GwgCsawyM/34HKVtGorCNEWV7C/m2HkX9FyQC4QcUR8xhNcDCNi+cJk5Tb1KO5RLLtGBZOklKGauWUYWx3Ajt2qL9WmbWdoU22tyJ/7GLny86TzHiwANAwg570xOMM+r2V9nH2J5gNJTZ1wesN/NT90CqDZriTImKb3ItF4iMB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
